from __future__ import annotations

from enum import StrEnum


class Side(StrEnum):
    BUY = "BUY"
    SELL = "SELL"

    @property
    def opposite(self) -> Side:
        return Side.SELL if self is Side.BUY else Side.BUY


class OrderType(StrEnum):
    LIMIT = "LIMIT"
    MARKET = "MARKET"


class TimeInForce(StrEnum):
    GTC = "GTC"
    IOC = "IOC"
    FOK = "FOK"
    POST_ONLY = "POST_ONLY"


class OrderStatus(StrEnum):
    NEW = "NEW"
    ACCEPTED = "ACCEPTED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


class EventType(StrEnum):
    ORDER_ACCEPTED = "ORDER_ACCEPTED"
    ORDER_REJECTED = "ORDER_REJECTED"
    TRADE_EXECUTED = "TRADE_EXECUTED"
    ORDER_PARTIALLY_FILLED = "ORDER_PARTIALLY_FILLED"
    ORDER_FILLED = "ORDER_FILLED"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    CANCEL_REJECTED = "CANCEL_REJECTED"
    ORDER_MODIFIED = "ORDER_MODIFIED"
    MODIFY_REJECTED = "MODIFY_REJECTED"
    BOOK_UPDATED = "BOOK_UPDATED"
    RISK_REJECTED = "RISK_REJECTED"


class RejectReason(StrEnum):
    DUPLICATE_ORDER_ID = "DUPLICATE_ORDER_ID"
    INVALID_QUANTITY = "INVALID_QUANTITY"
    INVALID_PRICE = "INVALID_PRICE"
    MARKET_REQUIRES_IOC_OR_FOK = "MARKET_REQUIRES_IOC_OR_FOK"
    POST_ONLY_WOULD_TRADE = "POST_ONLY_WOULD_TRADE"
    FOK_NOT_FILLABLE = "FOK_NOT_FILLABLE"
    UNKNOWN_ORDER = "UNKNOWN_ORDER"
    ORDER_NOT_LIVE = "ORDER_NOT_LIVE"
    INVALID_MODIFICATION = "INVALID_MODIFICATION"
    SELF_TRADE_PREVENTION = "SELF_TRADE_PREVENTION"
    RISK_MAX_ORDER_QUANTITY = "RISK_MAX_ORDER_QUANTITY"
    RISK_MAX_NOTIONAL = "RISK_MAX_NOTIONAL"
    RISK_MAX_LIVE_ORDERS = "RISK_MAX_LIVE_ORDERS"
    RISK_MAX_POSITION = "RISK_MAX_POSITION"
    RISK_MAX_EXPOSURE = "RISK_MAX_EXPOSURE"
    RISK_PRICE_COLLAR = "RISK_PRICE_COLLAR"
    RISK_SYMBOL_DISABLED = "RISK_SYMBOL_DISABLED"


class SelfTradePolicy(StrEnum):
    CANCEL_TAKER = "CANCEL_TAKER"
    ALLOW = "ALLOW"
